=== Rish4bh0/XML-gidt-card-store/catalog_20048981.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="giftcard_store">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="shop">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="store_name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]+" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="store_logo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="img">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="id" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="inventory">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="gift_card" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="giftcard_img">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="img">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="id" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:pattern value="steam|flight|apexlegends|google|valorant|razer|amazon|ebay|xsplit|twitch|crunchyroll|netflix|spotify|pubg|xbox|hulu|itunes|nintendo" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="type">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Digital" />
                                                    <xs:enumeration value="Physical" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="location" minOccurs="0">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="United States" />
                                                    <xs:enumeration value="Europe" />
                                                    <xs:enumeration value="United Kingdom" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="deliver" type="xs:string" minOccurs="0" />
                                        <xs:element name="discount" type="xs:string" minOccurs="0" />
                                        <xs:element name="valid" type="xs:string" minOccurs="0" />
                                        <xs:element name="description" type="xs:string" minOccurs="0" />
                                        <xs:element name="cost" type="xs:string" />
                                        <xs:element name="important_notice" type="xs:string" minOccurs="0" />
                                    </xs:sequence>
                                    <xs:attribute name="code" use="required" type="xs:string" />
                                    <xs:attribute name="balance" use="required" type="xs:nonNegativeInteger" />
                                    <xs:attribute name="enabled" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="True" />
                                                <xs:enumeration value="False" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="expired" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="True" />
                                                <xs:enumeration value="False" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="currency" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="Dollar|Pound|Euro"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="promo_code" use="optional" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="shop_details">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="store_address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="street" type="xs:string" />
                                        <xs:element name="city" type="xs:string" />
                                        <xs:element name="postal_code" type="xs:string" />
                                        <xs:element name="country" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="contact">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="telephone_number" type="xs:string" />
                                        <xs:element name="mobile_number" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="store_email" type="xs:string" />
                            <xs:element name="store_web_address" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="logo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="img">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="id" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="description2" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="SName" type="xs:string" fixed="Transacta" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Rish4bh0/XML-gidt-card-store/catalog_ 20048981.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<?xml-stylesheet href="catalog_20048981.css" type="text/css"?>

<giftcard_store SName="Transacta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20048981.xsd">
  <shop>
    <store_name>Transacta</store_name>
    <store_logo>
      <img id="logo"></img>
    </store_logo>
  </shop>
  <inventory>
    <gift_card code="saS432f" balance="50" enabled="False" expired="False" currency="Dollar" promo_code="Hyper">
      <giftcard_img>
        <img id="steam"></img>
      </giftcard_img>
      <name>Steam giftcard</name>
      <type>Digital</type>
      <location>United States</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 30% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description> Steam is the best choice for PC gaming available. Browse titles for over 3,500 games. </description>
      <cost>50$</cost>
      <important_notice>Important Notice: Due to recent changes made by Steam, you can only activate gift cards having the same currency that is configured in your steam account.</important_notice>
    </gift_card>
    <gift_card code="FSD5df" balance="20" enabled="False" expired="False" currency="Dollar" promo_code="Hyper">
      <giftcard_img>
        <img id="google"></img>
      </giftcard_img>
      <name>Google Play</name>
      <type>Digital</type>
      <location>United States</location>
      <deliver>Deliver time 10-15 min in our business hour</deliver>
      <discount>Use promocode Hyper for 15% off</discount>
      <cost>25$</cost>
      <important_notice>Important Notice: No expiration date. Code is valid only in UNITED STATES.</important_notice>
    </gift_card>
    <gift_card code="kf7dfS" balance="30" enabled="False" expired="False" currency="Dollar">
      <giftcard_img>
        <img id="valorant"></img>
      </giftcard_img>
      <name>Valorant gift card 100$</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 10-15 min</deliver>
      <valid>Expires on: 02/03/2023</valid>
      <description>Riot Games gift card is a digital RP voucher with an activation code that adds Riot Points to your selected Riot Games account.</description>
      <cost>100$</cost>
      <important_notice>Important Notice: Requires base game.</important_notice>
    </gift_card>
    <gift_card code="Hjd6S" balance="100" enabled="False" expired="False" currency="Dollar" promo_code="Hyper">
      <giftcard_img>
        <img id="razer"></img>
      </giftcard_img>
      <name>Razer Gold</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 15% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description>Use Razer Gold to buy games and in-game content to get more bang for your buck.</description>
      <cost>100$</cost>
    </gift_card>
    <gift_card code="js6Dd" balance="100" enabled="False" expired="False" currency="Dollar" promo_code="Hyper">
      <giftcard_img>
        <img id="itunes"></img>
      </giftcard_img>
      <name>iTunes Gift Card</name>
      <type>Physical</type>
      <discount>Promocode Hyper for 30% off</discount>
      <description>Buy 100 dollar iTunes card code and try this Apple service on your own iTunes account!</description>
      <cost>100$</cost>
      <important_notice>Important Notice: No expiration date. Code is valid only for the US AppStore.</important_notice>
    </gift_card>
    <gift_card code="kg5hf" balance="25" enabled="False" expired="False" currency="Pound">
      <giftcard_img>
        <img id="twitch"></img>
      </giftcard_img>
      <name>Twitch Gift Card</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <valid>Expires on: 02/03/2023</valid>
      <description>Once you activate this digital gift card, the equivalent of 25 USD will be added to your Twitch Wallet as Bits.</description>
      <cost>25$</cost>
    </gift_card>
    <gift_card code="klJD5" balance="50" enabled="False" expired="False" currency="Pound" promo_code="Hyper">
      <giftcard_img>
        <img id="amazon"></img>
      </giftcard_img>
      <name>Amazon Gift Card 50£</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 30% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description>When you buy Amazon Gift Card 50 GBP, you open a door for the receiver to pick and choose from a terrific variety of items.</description>
      <cost>50£</cost>
    </gift_card>
    <gift_card code="skldjf" balance="50" enabled="False" expired="False" currency="Dollar">
      <giftcard_img>
        <img id="hulu"></img>
      </giftcard_img>
      <name>HULU Gift Card</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <valid>Expires on: 02/03/2023</valid>
      <description>Hulu offers instant access to live and on demand channels, original series and films, and a premium library of TV and movies to more than 17 million subscribers in the U.S. Since its launch in 2008</description>
      <cost>50$</cost>
    </gift_card>
    <gift_card code="hdD4da" balance="30" enabled="False" expired="False" currency="Pound" promo_code="Hyper">
      <giftcard_img>
        <img id="xbox"></img>
      </giftcard_img>
      <name>Xbox Game Pass </name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 30% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description>All of the Xbox Game Pass games can be downloaded for an unlimited number of times throughout the duration of the membership.</description>
      <cost>30£</cost>
    </gift_card>
    <gift_card code="hD5FH" balance="25" enabled="False" expired="False" currency="Pound" promo_code="Hyper">
      <giftcard_img>
        <img id="pubg"></img>
      </giftcard_img>
      <name>PUBG UC</name>
      <type>Physical</type>
      <location>United Kingdom</location>
      <discount>Promocode Hyper for 30% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description>PUBG Survivor Pass: Vikendi is a DLC expansion to one of the most popular battle royale games of all time.</description>
      <cost>25£</cost>
      <important_notice>The base game PlayerUnknown’s Battlegrounds Steam key is required in order to play.</important_notice>
    </gift_card>
    <gift_card code="ds4F6H" balance="45" enabled="False" expired="False" currency="Pound" promo_code="Hyper">
      <giftcard_img>
        <img id="xsplit"></img>
      </giftcard_img>
      <name>XSplit</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 25% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <cost>45£</cost>
      <important_notice>Important Notice: In order to activate the key visit https://www.xsplit.com/redeem.</important_notice>
    </gift_card>
    <gift_card code="saS432f" balance="20" enabled="False" expired="False" currency="Dollar" promo_code="Hyper">
      <giftcard_img>
        <img id="crunchyroll"></img>
      </giftcard_img>
      <name>Crunchyroll</name>
      <type>Physical</type>
      <location>United States</location>
      <discount>Promocode Hyper for 30% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description>Welcome to VRV, the fan-first streaming service that connects the dots between anime, sci-fi, fantasy, cartoons, and more.</description>
      <cost>25$</cost>
    </gift_card>
    <gift_card code="saS432f" balance="25" enabled="False" expired="False" currency="Euro" promo_code="Hyper">
      <giftcard_img>
        <img id="netflix"></img>
      </giftcard_img>
      <name>Netflix </name>
      <type>Digital</type>
      <location>Europe</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 30% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description>Buy Netflix Gift Card 25 EUR and get yourself a subscription that fits your needs and wants.</description>
      <cost>25€</cost>
    </gift_card>
    <gift_card code="saS432f" balance="50" enabled="False" expired="False" currency="Dollar">
      <giftcard_img>
        <img id="ebay"></img>
      </giftcard_img>
      <name>Ebay</name>
      <type>Digital</type>
      <location>United States</location>
      <deliver>Deliver time 5-10 min</deliver>
      <valid>Expires on: 02/03/2023</valid>
      <description>eBay Gift Card with $50 prepaid credit for all your purchases on eBay.com.</description>
      <cost>50$</cost>
    </gift_card>
    <gift_card code="saS432f" balance="60" enabled="False" expired="False" currency="Pound" promo_code="Hyper">
      <giftcard_img>
        <img id="spotify"></img>
      </giftcard_img>
      <name>Spotify</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 30% off</discount>
      <valid>Expires on: 02/03/2023</valid>
      <description>Buy your Spotify gift card online to enjoy all benefits of a Spotify Premium subscription for 1, 3 or 6 months.</description>
      <cost>60$</cost>
    </gift_card>
    <gift_card code="saS432f" balance="20" enabled="False" expired="False" currency="Pound" promo_code="Hyper">
      <giftcard_img>
        <img id="nintendo"></img>
      </giftcard_img>
      <name>Nintendo</name>
      <type>Digital</type>
      <location>United Kingdom</location>
      <deliver>Deliver time 5-10 min</deliver>
      <discount>Promocode Hyper for 30% off</discount>
